version: '3.8'

services:
  ewm-service:
    build:
      context: ./main_service
      dockerfile: ./Dockerfile
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - main-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/ewm_main_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats_service:9090

  stats_service:
    build:
      context: ./stats_service
      dockerfile: ./Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats_db:
    image: postgres:15.3-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ewm_stats_db

  main-db:
    image: postgres:15.3-alpine
    container_name: main-db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm_main_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

